import Navbar from "@/components/Navbar";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Poppins, Playfair_Display } from "next/font/google";

export const metadata: Metadata = {
  title: "Law Firm",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${playfair.variable}`}
      suppressHydrationWarning
    >
      <body>
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
